from datetime import datetime
from typing import Annotated, Any

from pydantic import BaseModel, BeforeValidator, Field

from app.config.app import get_settings
from app.modules.authentication.account_state import NextAction
from app.modules.authentication.constants import CHANNEL_CODES, LoginChannel, TokenType


def _coerce_channel(value: Any) -> Any:
    """Accept the numeric channel codes mobile clients send (1 = CUSTOMER, ... 4 = ADMIN).

    The stored and returned value stays the string channel name; this only widens what is accepted
    on input so that `{"login_channel": 1}` is not rejected with a 422.
    """
    if isinstance(value, bool):
        return value
    if isinstance(value, int):
        return CHANNEL_CODES.get(value, value)
    if isinstance(value, str) and value.isdigit():
        return CHANNEL_CODES.get(int(value), value)
    return value


ChannelField = Annotated[LoginChannel, BeforeValidator(_coerce_channel)]

# The documented pattern follows the configured code length; the service re-checks the length per request.
OTP_PATTERN = rf"^[0-9]{{{get_settings().otp_length}}}$"

USER_TYPES = {
    LoginChannel.CUSTOMER: "CUSTOMER",
    LoginChannel.DELIVERY: "DELIVERY_PARTNER",
    LoginChannel.MERCHANT: "MERCHANT_STAFF",
    LoginChannel.ADMIN: "ADMIN",
}


def user_type_for_channel(channel: LoginChannel) -> str:
    return USER_TYPES[channel]


class DeviceInfo(BaseModel):
    device_id: str | None = Field(default=None, max_length=100, description="Stable install ID generated by the app.")
    device_type: str | None = Field(default=None, max_length=20, description="android or ios.")
    device_name: str | None = Field(default=None, max_length=100)
    app_version: str | None = Field(default=None, max_length=40)
    fcm_token: str | None = Field(
        default=None,
        max_length=512,
        description="Push token. Stored on the session created by OTP verification or refresh and cleared on logout.",
    )


class OTPRequest(BaseModel):
    mobile_number: str = Field(min_length=6, max_length=15)
    country_code: str = Field(default="+91", min_length=1, max_length=5)
    login_channel: ChannelField = Field(
        default=LoginChannel.CUSTOMER,
        description="Ignored: the app channel is taken from the URL. Accepts the name or the numeric code (1 CUSTOMER, 2 DELIVERY, 3 MERCHANT, 4 ADMIN).",
        deprecated=True,
    )
    device: DeviceInfo | None = None


class OTPRequestResponse(BaseModel):
    request_id: str
    message: str = "OTP request accepted"
    expires_in: int
    resend_after: int
    code: str = "OTP_REQUEST_ACCEPTED"
    dev_otp: str | None = Field(
        default=None,
        description=(
            "The plaintext code, for app development only. Present only while "
            "DEV_EXPOSE_OTP_IN_RESPONSE is on, which the settings validator refuses outside "
            "local/development/test. Always null in staging and production."
        ),
    )


class OTPVerifyRequest(BaseModel):
    request_id: str = Field(min_length=1, max_length=36)
    mobile_number: str | None = Field(default=None, min_length=6, max_length=15, description="Ignored.", deprecated=True)
    country_code: str = Field(default="+91", min_length=1, max_length=5, description="Ignored.", deprecated=True)
    login_channel: ChannelField = Field(
        default=LoginChannel.CUSTOMER,
        description="Ignored. Accepts the name or the numeric code (1 CUSTOMER, 2 DELIVERY, 3 MERCHANT, 4 ADMIN).",
        deprecated=True,
    )
    otp: str = Field(pattern=OTP_PATTERN, description="Numeric code with OTP_LENGTH digits (4 in the current configuration).")
    device: DeviceInfo | None = None


class TokenPair(BaseModel):
    access_token: str
    refresh_token: str
    token_type: TokenType = TokenType.BEARER
    expires_in: int = Field(description="Access-token lifetime in seconds.")


class MerchantSummary(BaseModel):
    id: str
    code: str
    name: str
    status: str
    approval_status: str
    staff_type: str | None = None


class DeliveryProfileSummary(BaseModel):
    id: str
    delivery_user_type: str
    employee_code: str | None = None
    status: str
    approval_status: str


class CustomerProfileSummary(BaseModel):
    id: str
    customer_type: str | None = None
    name: str | None = None
    merchant_code: str | None = None
    status: str
    rejection_reason: str | None = None
    submitted_at: datetime | None = None


class AccountFields(BaseModel):
    """Fields shared by OTP verification and /me that drive mobile navigation."""

    user_id: str
    login_channel: LoginChannel
    user_type: str = Field(description="CUSTOMER, DELIVERY_PARTNER, MERCHANT_STAFF or ADMIN.")
    session_type: str = Field(description="`access` (full app session) or `onboarding` (customer registration only).")
    role: str | None = Field(default=None, description="Primary role code for this app, e.g. manager, driver, customer.")
    active_roles: list[str] = Field(default_factory=list, description="Distinct role codes allowed on this app.")
    account_status: str
    approval_status: str | None = Field(default=None, description="Merchant, delivery-profile or customer approval state.")
    profile_completion_status: str | None = Field(default=None, description="Customer only: NOT_STARTED, INCOMPLETE or COMPLETE.")
    next_action: NextAction
    merchant: MerchantSummary | None = Field(default=None, description="Merchant and delivery apps only.")
    delivery_profile: DeliveryProfileSummary | None = Field(default=None, description="Delivery app only.")
    customer_profile: CustomerProfileSummary | None = Field(default=None, description="Customer app only, once details are submitted.")


class OTPVerifyResponse(AccountFields):
    token: TokenPair
    is_new_user: bool = Field(default=False, description="True when this verification created the account.")
    code: str = "OTP_VERIFIED"
    message: str = "OTP verified"


class OTPResendRequest(BaseModel):
    request_id: str = Field(min_length=1, max_length=36)
    device: DeviceInfo | None = None


class RefreshTokenRequest(BaseModel):
    refresh_token: str = Field(min_length=1)
    device_id: str | None = Field(default=None, max_length=100, description="Deprecated: use device.device_id.", deprecated=True)
    device: DeviceInfo | None = Field(default=None, description="Send when the push token or app version changed; omitted values are kept.")


class LogoutRequest(BaseModel):
    refresh_token: str | None = None
    device_id: str | None = Field(default=None, description="Ignored.", deprecated=True)


class CurrentUserResponse(AccountFields):
    display_name: str | None = None
    mobile_number: str | None = None
    country_code: str | None = None
    effective_permissions: list[str] = Field(default_factory=list)
    status: str = Field(description="Deprecated: same value as account_status.", deprecated=True)
    profile: DeliveryProfileSummary | CustomerProfileSummary | None = Field(
        default=None,
        description="Deprecated: use delivery_profile or customer_profile.",
        deprecated=True,
    )
