from enum import StrEnum


class UserRole(StrEnum):
    CUSTOMER = "CUSTOMER"
    DELIVERY_PARTNER = "DELIVERY_PARTNER"
    MERCHANT = "MERCHANT"
    ADMIN = "ADMIN"
    MANAGER = "MANAGER"
    SALESPERSON = "SALESPERSON"
    GODOWN_STOCK_MANAGER = "GODOWN_STOCK_MANAGER"
    ACCOUNTANT = "ACCOUNTANT"
    DRIVER = "DRIVER"
    HELPER = "HELPER"
