"""Private local-filesystem storage provider.

For development, tests and any deployment that has explicitly approved local storage. Files
live under a configured root that is **never** mounted into static-file middleware, so the
only way to read one is through an authorised route.

Three things make the key safe: it is generated by the application (never derived from the
uploaded filename), it is re-validated on every read, and the resolved path is checked to be
inside the root before any file is opened. That last check is what stops a traversal like
``../../etc/passwd`` even if a crafted key ever reached this layer.
"""

import hashlib
import os
import re
from pathlib import Path

import anyio

from app.shared.storage.provider import StorageProvider, StoredObject

# Keys this provider will accept: segments of url-safe characters separated by "/".
SAFE_KEY = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*(/[A-Za-z0-9][A-Za-z0-9._-]*)*$")
CHUNK_SIZE = 64 * 1024


class UnsafeStorageKeyError(ValueError):
    """The key could escape the storage root, or is not in the accepted form."""


class LocalStorageProvider(StorageProvider):
    name = "local"

    def __init__(self, root: str | Path) -> None:
        self._root = Path(root).resolve()
        self._root.mkdir(parents=True, exist_ok=True)

    def _path(self, key: str) -> Path:
        if not key or ".." in key or key.startswith("/") or not SAFE_KEY.match(key):
            raise UnsafeStorageKeyError("Unsafe storage key")
        # Resolved against the root, then proved to be inside it — a symlink planted in the
        # tree would otherwise resolve outside while the string still looked relative.
        candidate = (self._root / key).resolve()
        if candidate != self._root and self._root not in candidate.parents:
            raise UnsafeStorageKeyError("Storage key resolves outside the storage root")
        return candidate

    async def save(self, key: str, chunks) -> StoredObject:
        path = self._path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        digest = hashlib.sha256()
        size = 0
        # Written to a temporary name first: a reader can never observe a half-written file,
        # and a failed upload leaves no object behind under the real key.
        staging = path.with_name(path.name + ".part")
        try:
            async with await anyio.open_file(staging, "wb") as handle:
                async for chunk in chunks:
                    digest.update(chunk)
                    size += len(chunk)
                    await handle.write(chunk)
            await anyio.to_thread.run_sync(os.replace, staging, path)
        except BaseException:
            staging.unlink(missing_ok=True)
            raise
        return StoredObject(storage_key=key, size=size, checksum_sha256=digest.hexdigest())

    def open(self, key: str):
        """Validate the key **now** and return an iterator over the bytes.

        Deliberately not an ``async def`` generator: that would defer the traversal check
        until the caller pulled the first chunk, so a route could build a streaming response
        around an unsafe key and only fail once the headers were already sent.
        """
        path = self._path(key)
        if not path.is_file():
            raise FileNotFoundError(key)

        async def stream():
            async with await anyio.open_file(path, "rb") as handle:
                while chunk := await handle.read(CHUNK_SIZE):
                    yield chunk

        return stream()

    async def delete(self, key: str) -> None:
        try:
            self._path(key).unlink(missing_ok=True)
        except UnsafeStorageKeyError:
            # Nothing was ever stored under an unsafe key, so there is nothing to delete.
            return
